### ISSUE TITLE
Add SSL certificates chain management

### ISSUE THREAD

**Issue by vickrame** [emilevauge/traefik#101]
Il serait intéressant de pouvoir ajouter une chaine de certificat. Aujourd'hui on ne peut qu'ajouter que la clef et le certificat.

Le but serait se pouvoir dialoguer avec un backend sans avoir l'erreur SNI.

Pour rappel voila le code côté HAProxy:
backend bk_www_cca
    mode http   
    log 127.0.0.1   local1
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    http-request add-header X-Forwarded-Host "rlon6666-cca.intra.laposte.fr"
    http-request set-header Host "rlon6667-cca.intra.laposte.fr"
    http-request set-header Referer "rlon6666-cca.intra.laposte.fr"
    # ProxyPassReverseCookieDomain bk.dom.com dom.com
    acl hdr_set_cookie_dom res.hdr(Set-cookie) -m sub Domain= .rlon6667-cca.intra.laposte.fr
    rspirep ^(Set-Cookie:.*)\ Domain=.rlon6667-cca.intra.laposte.fr(.*) \1\ Domain=.rlon6666-cca.intra.laposte.fr\2 if hdr_set_cookie_dom   
    acl hdr_location res.hdr(Location) -m found
    rspirep ^Location:\ (http|https)://rlon6667-cca.intra.laposte.fr\/(.*) Location:\ \1://rlon6666-cca.intra.laposte.fr/\2 if hdr_location
    #http-response lua.cca2
    server cca rlon6667-cca.intra.laposte.fr:443 check ssl sni req.hdr(host) verify none no-ssl-reuse

**Comment by vdemeester** [comment]
Same as on the other one, in english it would be better :stuck_out_tongue_closed_eyes:
