### ISSUE TITLE
passHostHeader with kv backends not working

### ISSUE THREAD

**Issue by bennyhansson** [emilevauge/traefik#107]
Release: v1.0.alpha.275

**Comment by emilevauge** [comment]
Hi @bennyhansson, thank you for submitting.
The template should be updated: https://github.com/emilevauge/traefik/blob/master/templates/kv.tmpl#L27

**Comment by bennyhansson** [comment]
Like this ?
https://gist.github.com/bennyhansson/a2345a9a60e1fe595cf8#file-kv-tmpl-L31

**Comment by emilevauge** [comment]
Hi @bennyhansson, yep that's right :)
But the documentation should also be updated.
Would make a PR on that?
