### ISSUE TITLE
Support Marathon Authentication and SSL key verification

### ISSUE THREAD

**Issue by stevendborrelli** [emilevauge/traefik#110]
In order to use traefik in secured marathon environments we would like to see traefik support authenticating to marathon. go-marathon support Basic Authentication.

As part of this, we'd like to look into disabling SSL verification (this may be an update in go-marathon).

**Comment by zubairov** [comment]
+1

**Comment by emilevauge** [comment]
Created an issue to add (insecure) TLS support in go-marathon: https://github.com/gambol99/go-marathon/issues/122
