### ISSUE TITLE
Marathon template fails if the path contains a directory in it.

### ISSUE THREAD

**Issue by nsf** [emilevauge/traefik#115]
If you say in a config file something like this:
```
[marathon]
filename = "/etc/traefik/marathon.tmpl"
```

It fails. Because "text/template" API is used incorrectly.

You pass a full path as a name of the template here:
https://github.com/emilevauge/traefik/blob/master/provider/marathon.go#L187

And you then ParseFiles with the same path:
https://github.com/emilevauge/traefik/blob/master/provider/marathon.go#L189

It fails, because this is exactly the case ParseFiles documentation warns about. Quoting the docs:

> ParseFiles parses the named files and associates the resulting templates with t. If an error occurs, parsing stops and the returned template is nil; otherwise it is t. There must be at least one file. **Since the templates created by ParseFiles are named by the base names of the argument files, t should usually have the name of one of the (base) names of the files**. If it does not, depending on t's contents before calling ParseFiles, t.Execute may fail. In that case use t.ExecuteTemplate to execute a valid template.

**Comment by nsf** [comment]
Affects other provides as well. Suggested fix, create a template with `filepath.Base(provider.Filename)` as a name.

**Comment by vdemeester** [comment]
There is a PR that is fixing that

**Comment by vdemeester** [comment]
#108 it is :-)
