### ISSUE TITLE
passHostHeader datatype mismatch with kv backend

### ISSUE THREAD

**Issue by bennyhansson** [emilevauge/traefik#117]
Error creating kv configuration:Type mismatch for 'types.Configuration.Frontends': Type mismatch for 'types.Frontend.PassHostHeader': Expected boolean but found 'string'

"/traefik/frontends/frontend1/passHostHeader" "true"

Can we type cast to boolean ?

**Comment by emilevauge** [comment]
Hi @bennyhansson, did you test your own PR #112 before submitting ?

**Comment by bennyhansson** [comment]
Of cause not. I don't want to steal the end users job :)

I had almost identical "file" and etcd configurations and I didn't notice it was only the "file" backend that was working.

My bad!

Can we change the passHostHeader type to integer (1,0 / true, false) ?

**Comment by bennyhansson** [comment]
Still not working with etcd!

Release: v1.0.alpha.311

level=error msg="Type mismatch for 'types.Configuration.Frontends': Type mismatch for 'types.Frontend.PassHostHeader': Expected boolean but found 'string'."

Can we change boolean properties to strings to simplify for KV backends ?
