### ISSUE TITLE
Leverage PortIndex for traefik.port instead of actual port definition for Marathon backend

### ISSUE THREAD

**Issue by dontrebootme** [emilevauge/traefik#130]
When deploying a service with multiple ports and `hostPort: 0`, its unclear how I can leverage `traefik.port` to label which port I want Traefik to balance. Leveraging portIndex would align the functionality with the Marathon Health Checks design: https://mesosphere.github.io/marathon/docs/health-checks.html.

**Comment by keis** [comment]
I'm setting `traefik.port` to be the `containerPort` I'm using and that works fine with `hostPort: 0`. But I guess having both couldn't hurt :)

**Comment by emilevauge** [comment]
@kels, `traefik.port` label is currently not used in Traefik with marathon. It works in your case because your app exposes only one port ;)

**Comment by emilevauge** [comment]
Fixed by https://github.com/emilevauge/traefik/pull/138
