### ISSUE TITLE
 build traefik error

### ISSUE THREAD

**Issue by pangzheng** [emilevauge/traefik#140]
build error log 

+ go get github.com/mitchellh/gox
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/usr/local/go/bin:/root/go/bin
+ go get github.com/emilevauge/traefik
../../emilevauge/traefik/web.go:11:2: no buildable Go source files in /root/go/src/github.com/emilevauge/traefik/autogen

change  step  go get github.com/emilevauge/traefik to git clone and run build ok~

**Comment by vdemeester** [comment]
hi @pangzheng,

The problem is the `go generate` step — `go get` get the sources and then build them. To make it work (maybe we should update the documentation about that):

```bash
$ go get github.com/mitchellh/gox
$ go get github.com/jteeuwen/go-bindata/...
$ go get -d github.com/emilevauge/traefik # it might print a warning but it's no biggies
$ go generate github.com/emilevauge/traefik
$ go get github.com/emilevauge/traefik
```

**Comment by emilevauge** [comment]
I'm more and more tempted by vendoring dependances in a near futur (and also generated code). This would simplify the build process by just calling `go get github.com/emilevauge/traefik`.

**Comment by vdemeester** [comment]
@emilevauge :heart_eyes_cat:

**Comment by pangzheng** [comment]
this is ok ?  or need install cookoo?
log info:

+ go get github.com/mitchellh/gox
+ go get github.com/Masterminds/cookoo
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/usr/local/go/bin:/root/go/bin
+ go get -d github.com/emilevauge/traefik
../../emilevauge/traefik/web.go:11:2: no buildable Go source files in /root/go/src/github.com/emilevauge/traefik/autogen
+ go generate github.com/emilevauge/traefik
+ go get github.com/emilevauge/traefik
+ glide up --update-vendored github.com/emilevauge/traefik
[WARN] Failed to set version on github.com/Masterminds/cookoo to master: The Remote does not match the VCS endpoint
[INFO] Detected semantic version. Setting version for github.com/Masterminds/vcs to 1.3.0.
[INFO] Detected semantic version. Setting version for github.com/Masterminds/semver to 1.0.0.
[INFO] Package github.com/emilevauge/traefik manages its own dependencies
[INFO] Detected semantic version. Setting version for github.com/Masterminds/vcs to 1.3.0.
[INFO] Detected semantic version. Setting version for github.com/Masterminds/semver to 1.0.0.
[WARN] Problem setting version on github.com/Masterminds/cookoo: The Remote does not match the VCS endpoint (flatten)
[INFO] Project relies on 5 dependencies.

**Comment by pangzheng** [comment]
and test run error 

+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
+ export GOROOT=/usr/local/go
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/usr/local/go/bin
+ export GOPATH=/root/go
+ export GO15VENDOREXPERIMENT=1
+ cd /root/go/src/github.com/emilevauge/traefik
+ go test ./...
# github.com/emilevauge/traefik/integration
integration/docker_test.go:12:2: cannot find package "github.com/docker/docker/opts" in any of:
	/root/go/src/github.com/emilevauge/traefik/vendor/github.com/docker/docker/opts (vendor tree)
	/usr/local/go/src/github.com/docker/docker/opts (from $GOROOT)
	/root/go/src/github.com/docker/docker/opts (from $GOPATH)
FAIL	github.com/emilevauge/traefik/integration [setup failed]
?   	github.com/emilevauge/traefik	[no test files]
?   	github.com/emilevauge/traefik/autogen	[no test files]
ok  	github.com/emilevauge/traefik/integration/utils	0.017s
?   	github.com/emilevauge/traefik/middlewares	[no test files]
--- FAIL: TestDockerLoadDockerConfig (0.00s)
	docker_test.go:785: expected map[string]*types.Frontend{"\"frontend-Host-test-docker-localhost\"":(*types.Frontend)(0xc82013a280)}, got map[string]*types.Frontend{"frontend-Host-test-docker-localhost":(*types.Frontend)(0xc82013baa0)}
time="2015-12-08T08:46:21Z" level=error msg="Error getting keys: anythingError"
time="2015-12-08T08:46:21Z" level=error msg="Error getting key: anythingError"
time="2015-12-08T08:46:21Z" level=error msg="Failed to create a client for marathon, error: error"
time="2015-12-08T08:46:21Z" level=error msg="Failed to create a client for marathon, error: error"
time="2015-12-08T08:46:21Z" level=error msg="Unable to get marathon application from task test"
time="2015-12-08T08:46:21Z" level=error msg="Unable to get marathon application from task test"
time="2015-12-08T08:46:21Z" level=error msg="Unable to get marathon application from task "
time="2015-12-08T08:46:21Z" level=error msg="Unable to get marathon application from task test2"
time="2015-12-08T08:46:21Z" level=error msg="Unable to get marathon application from task "
time="2015-12-08T08:46:21Z" level=error msg="Unable to get marathon application from task test2"
--- FAIL: TestConfigurationErrors (0.00s)
	provider_test.go:90: should have generate an error with "Near line 1, key 'Hello': Near line 1: Expected key separator '=', but got '<' instead", got Near line 1 (last key parsed 'Hello'): Expected key separator '=', but got '<' instead.
FAIL
FAIL	github.com/emilevauge/traefik/provider	0.008s
?   	github.com/emilevauge/traefik/types	[no test files]
?   	github.com/emilevauge/traefik/vendor/github.com/docker/docker/autogen/dockerversion	[no test files]

**Comment by emilevauge** [comment]
@pangzheng did you use glide?

**Comment by pangzheng** [comment]
install shell

#!/bin/bash
set -x
export PATH=$PATH:/usr/local/go/bin && \
export GOROOT=/usr/local/go && \
export PATH=$PATH:$GOROOT/bin && \
export GOPATH=$HOME/go && \
export GO15VENDOREXPERIMENT=1 && \
#install go-bindata
go get github.com/jteeuwen/go-bindata/... && \

#install glide
go get github.com/Masterminds/glide && \
cd $GOPATH/src/github.com/Masterminds/glide && \
make bootstrap && make build

#install gox
go get github.com/mitchellh/gox && \

#install cookoo
go get github.com/Masterminds/cookoo && \
export PATH=$PATH:$GOPATH/bin && \

#install traefik
go get -d github.com/emilevauge/traefik
go generate github.com/emilevauge/traefik && \
go get github.com/emilevauge/traefik && \
glide up --update-vendored github.com/emilevauge/traefik && \
go generate github.com/emilevauge/traefik && \
go build github.com/emilevauge/traefik
#test traefik
cd $GOPATH/src/github.com/emilevauge/traefik && \
go test github.com/emilevauge/traefik

**Comment by batwicket** [comment]
I've probably missed it, but is there a document somewhere which describes how traefik should be built? The nginx and haProxy projects both have detailed versioning and build instructions. Administrators of the bigger sites want to know exactly what they are putting on their systems. I don't see any explicit versioning in this script so it isn't apparent to me what exactly is being pulled in. Perhaps i'm missing something.

**Comment by batwicket** [comment]
perhaps of interest if you haven't seen it before.. http://12factor.net/dependencies. Just trying to be constructive. As i say, i've probably missed something.

**Comment by emilevauge** [comment]
@batwicket on the first page, you will find a contributing section: https://github.com/containous/traefik#contributing that explains how to build traefik.

**Comment by batwicket** [comment]
Thanks! I see you are using glide for versioning.
