### ISSUE TITLE
Is there a reason the consul support does not include use of the service definitions

### ISSUE THREAD

**Issue by BrianAdams** [emilevauge/traefik#146]
The documentation makes it appear that consul is simply used as a KV backend store.  Yet consul supports service discovery.  Is there any reason not to extend the consul backend so that traefik registers the backends from the the service registrations?

**Comment by emilevauge** [comment]
Hi @BrianAdams, as soon as Consul services allows labels (and not only tags), Traefik will support it.
https://github.com/hashicorp/consul/issues/997

**Comment by emilevauge** [comment]
Closing it for now.
