### ISSUE TITLE
Documentation: Assigning certificate files to HTTP backend

### ISSUE THREAD

**Issue by strarsis** [emilevauge/traefik#147]
I can't find a sample or description in the documentation 
about how to assign certificates for TLS/SSL to a HTTP backend 
dynamically, using prefix/HTTP API and/or vault as backend?

Thank you and
with best regards

**Comment by emilevauge** [comment]
@strarsis, for now you can't do that. Sorry.

**Comment by emilevauge** [comment]
Closing it for now.
