### ISSUE TITLE
Docker container: Administrative port not working

### ISSUE THREAD

**Issue by strarsis** [emilevauge/traefik#152]
I used this sample command from the Readme:
````
docker run -d -p 8080:8080 -p 80:80 -v $PWD/traefik.toml:/traefik.toml emilevauge/traefik
````

Port 80 is reachable, I get a 404 from traefik.
However, on port 8080 I get the connection refused.

Docker lists both those ports as bound for traefik container:
````
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                      PORTS                                                                                NAMES
8e493c548890        emilevauge/traefik             "/traefik"               14 seconds ago      Up 13 seconds               0.0.0.0:80->80/tcp, 0.0.0.0:8080->8080/tcp                                           boring_euclid
````

Thank you and
with best regards

**Comment by PierreZ** [comment]
Did you create your configuration file at the location where you are running this command? Because you're binding your current location as a docker volume (-v $PWD/traefik.toml:/traefik.toml)

**Comment by emilevauge** [comment]
As @PierreZ said, I assume that your configuration file `$PWD/traefik.toml` is empty.

**Comment by strarsis** [comment]
I checked this and there is a traefik.toml ([the example one](https://raw.githubusercontent.com/EmileVauge/traefik/master/traefik.sample.toml)) at $PWD/traefik.toml from where I run the docker container.

With best regards

**Comment by vdemeester** [comment]
@strarsis can you post the content of the `traefik.toml` ? the administrative/web part of traefik is commented out by default (and thus not enabled).

**Comment by strarsis** [comment]
https://gist.github.com/strarsis/ab307a7c1efbae45bc45

Is there a way to definitely check whether traefik inside the container got the right config file?

**Comment by vdemeester** [comment]
@strarsis you need to uncomment `# [web]` too (line 67).

You could `docker exec` inside to check, something like :

```bash
$ docker exec 8e493c548890 cat /traefik.toml
```

**Comment by strarsis** [comment]
I updated the gist, with [web] I can now reach the admin GUI.
