### ISSUE TITLE
Hostname/URL based routing

### ISSUE THREAD

**Issue by strarsis** [emilevauge/traefik#154]
Traefik documentation for Consul:
https://github.com/emilevauge/traefik/blob/master/docs/index.md#-consul-backend

How can I map an url or hostname to a backend (e.g. a Consul service (Docker container))?
/url seems to be the URL to the backend traefik should use, not the URL to be requested from the outside.

Thank you and 
with best regards

**Comment by doublerebel** [comment]
According to those docs (just a little farther down), external routes are mapped to a frontend, and that frontend is mapped to a backend.

**Comment by emilevauge** [comment]
Hi @strarsis, can I close the issue ?

**Comment by strarsis** [comment]
Yes.
