### ISSUE TITLE
multi path prefix

### ISSUE THREAD

**Issue by mougeli** [emilevauge/traefik#158]
i want to route /@_@ & /js & /css to a container while other paths to anothor container,
so the path reg shoud be /{url:(@_@|js|css)} and /{url:(?!@_@|js|css)}
however the last one reg doesnt work~,
whats the right format of the traefik path reg?

**Comment by emilevauge** [comment]
Hi @mougeli, regex are matched by gorilla/mux toolkit: http://www.gorillatoolkit.org/pkg/mux#Route.Host.
What is the point of your second pattern exactly?

**Comment by emilevauge** [comment]
@mougeli closing it, you can reopen it if you need further help.
