### ISSUE TITLE
Traefik filters Marathon application if the application has no port specified

### ISSUE THREAD

**Issue by akunaatrium** [emilevauge/traefik#162]
I am not sure if I am using Traefik correctly but something looks suspicious to me.
Namely, I have an app running in two backends and the app has been assigned a random port by Marathon, like this:

1) 55.55.55.11:31769
2) 55.55.55.12:31492

The application has these labels in Marathon:
    traefik.backend=foo
    traefik.frontend.rule=Path
    traefik.frontend.value=/mypath

then in my case Traefik outputs the following to the DEBUG log:

"Filtering marathon task without port %s/nodeapp"

And consequently the Traefik web interface does not list the app and load balancing is not of course working. I would expect Traefic to detect the ports 31769 and 31492 and register the application to be load-balanced.

A workaround is to just write some arbitrary port number to the applications ports in the Configuration dialog and save the configuration, after which Traefik determines the correct ports and registers the app correctly and load balancing works.

**Comment by emilevauge** [comment]
Hi @akunaatrium, thanks to @dylanmei, in the [last version](https://github.com/emilevauge/traefik/pull/138) of Traefik, you can use the label `traefik.portIndex` as seen here: https://github.com/emilevauge/traefik/blob/master/docs/index.md#marathon. It allows Traefik to use marathon random ports. Is it useful ?

**Comment by akunaatrium** [comment]
Hi! Nope, sorry, not working. Tried with traefik.portIndex with values 0 and 1, still the same result.

**Comment by akunaatrium** [comment]
I think it's worth noting that I am using Traefik through Docker image emilevauge/traefik:latest. Could be that this verison at Docker Hub does not yet contain the fix?

**Comment by emilevauge** [comment]
Maybe yes, could you update your traefik image?

**Comment by dylanmei** [comment]
Hello @akunaatrium 

The task is filtered out because Traefik gets no `port` info from marathon. I imagine you will have the same problem regardless of the newness of your docker image.

[marathon.go](https://github.com/emilevauge/traefik/blob/master/provider/marathon.go#L122-L125)

So I'd like to know more about your version of Marathon, and if you could show some more of your marathon json that would help.

**Comment by akunaatrium** [comment]
I will soon be able to get the Marathon version and application json when I get home but first I would like to elaborate on this a bit more. I just assume that the task.Ports value in the taskFilter function is the list of ports that I can manually enter to the Marathon application configuration. When I enter one completely random number to the configuration as the port (which is actually not used in any way), Traefik suddenly is able to get all the correct *Marathon assigned* ports (31769, 31492) and registers the application. Can't Traefik retrieve the Marathon assigned ports (in my case 31769 for one task and 31492 for the second task) without having to manually have anything written the Ports field? I may be missing something obvious also because I am actually just starting out with Mesos/Marathon.

**Comment by akunaatrium** [comment]
The application's JSON looks like this (retrieved with Marathon REST API call to GET /v2/apps/nodeapp):
```json
{
    "app": {
        "acceptedResourceRoles": null,
        "args": null,
        "backoffFactor": 1.15,
        "backoffSeconds": 1,
        "cmd": "node /home/vagrant/app/app.js",
        "constraints": [
            [
                "hostname",
                "UNIQUE"
            ]
        ],
        "container": null,
        "cpus": 0.1,
        "dependencies": [],
        "deployments": [],
        "disk": 0,
        "env": {},
        "executor": "",
        "healthChecks": [],
        "id": "/nodeapp",
        "instances": 2,
        "labels": {
            "traefik.backend": "foo",
            "traefik.frontend.rule": "Path",
            "traefik.frontend.value": "/mypath"
        },
        "lastTaskFailure": {
            "appId": "/nodeapp",
            "host": "55.55.55.12",
            "message": "Reconciliation: Task is unknown",
            "slaveId": "1f0c708c-ff03-43f5-887b-97a28558e043-S2",
            "state": "TASK_LOST",
            "taskId": "nodeapp.ec2e8e48-bb06-11e5-a537-024233626ade",
            "timestamp": "2016-01-15T18:07:51.638Z",
            "version": "2016-01-14T21:36:51.098Z"
        },
        "maxLaunchDelaySeconds": 3600,
        "mem": 16,
        "ports": [
            1234
        ],
        "requirePorts": false,
        "storeUrls": [],
        "tasks": [
            {
                "appId": "/nodeapp",
                "host": "55.55.55.11",
                "id": "nodeapp.0f43151d-bbb4-11e5-89ce-024219c79614",
                "ports": [
                    31690
                ],
                "slaveId": "5c22aec6-4c05-479f-9b8c-5aa5c68343b6-S0",
                "stagedAt": "2016-01-15T18:16:12.923Z",
                "startedAt": "2016-01-15T18:16:13.022Z",
                "version": "2016-01-15T18:16:12.886Z"
            },
            {
                "appId": "/nodeapp",
                "host": "55.55.55.12",
                "id": "nodeapp.12a63d4e-bbb4-11e5-89ce-024219c79614",
                "ports": [
                    31643
                ],
                "slaveId": "5c22aec6-4c05-479f-9b8c-5aa5c68343b6-S1",
                "stagedAt": "2016-01-15T18:16:18.606Z",
                "startedAt": "2016-01-15T18:16:18.682Z",
                "version": "2016-01-15T18:16:18.541Z"
            }
        ],
        "tasksHealthy": 0,
        "tasksRunning": 2,
        "tasksStaged": 0,
        "tasksUnhealthy": 0,
        "upgradeStrategy": {
            "maximumOverCapacity": 1,
            "minimumHealthCapacity": 1
        },
        "uris": [],
        "user": null,
        "version": "2016-01-15T18:16:18.541Z",
        "versionInfo": {
            "lastConfigChangeAt": "2016-01-15T18:12:18.389Z",
            "lastScalingAt": "2016-01-15T18:16:18.541Z"
        }
    }
}
```

And version of Marathon is: 0.13.0.

**Comment by dylanmei** [comment]
You'll want to declare your ports, even if you're happy for marathon to select random ports.

https://mesosphere.github.io/marathon/docs/rest-api.html
```
ports (Array of Integers)
The port array currently serves multiple roles:

The number of items in the array determines how many dynamic ports are allocated for every task.
For *every port that is zero*, a globally unique (cluster-wide) port is assigned and provided as part of the app definition to be used in load balancing definitions.
```

So in your case add `"ports": [0]` -- marathon will select the port for you and traefik will send traffic to that port.

**Comment by akunaatrium** [comment]
Ok, so that's how the logic is indeed then. Thanks for clarification.
