### ISSUE TITLE
assigning different containers to the same backend through marathon

### ISSUE THREAD

**Issue by tayzlor** [emilevauge/traefik#170]
According to the docs it states (in the marathon backend) that you can add labels to override the default behaviour - 

```
traefik.backend=foo: assign the application to foo backend
```

from reading this it reads to me if I add a label to an app that specifies another services backend it would get added there. This would allow you to do a kind of A/B testing while you add an app to another backend temporarily (which would take a % of traffic)

I've tried this using the following marathon.json snippets

start app 1 with  ```id:nginx```

start app 2 with ```id:nginx-v2```

in ```nginx-v2``` JSON file add the following label -

```
  "labels": {
     "traefik.backend": "backend-nginx"
  },
```

Instead of adding to the first nginx app backend, it goes and creates a whole new frontend and backend for it. Which means I have 2 apps on 2 different URLs (nginx.domain and nginx-v2.domain)

This looks like because here https://github.com/emilevauge/traefik/blob/master/templates/marathon.tmpl it interpolates the ID to form the template.

Question is then, are the docs wrong or out of date? Or should this be actually working? 
If we look in the docker template, it actually looks up the backend via ```getBackend``` - 

https://github.com/emilevauge/traefik/blob/master/templates/docker.tmpl 

but getBackend is not implemented in the marathon plugin.

**Comment by tayzlor** [comment]
I'll have a crack at providing a fix for the marathon plugin to use getBackend

**Comment by emilevauge** [comment]
Hi @tayzlor, the doc was wrong on that point (copy/paste from Docker provider I think).
This behavior was intended as I thought it would not be required in Marathon.
But if you need it, I have no problem to add it :)

**Comment by tayzlor** [comment]
PR for this in #171
