### ISSUE TITLE
Consul catalog backend

### ISSUE THREAD

**Issue by keis** [emilevauge/traefik#176]
Hey. It would be really sweet if traefik could use the catalog api of consul as a backend. Is this something you have planned to add or would want to include?

cheers!

**Comment by emilevauge** [comment]
Hi @keis, yes I agree, but as I said here: https://github.com/emilevauge/traefik/issues/146, there is no label notion in Consul services. Maybe I could use tags using a special format but it would have been better with labels :)

**Comment by keis** [comment]
It would be useful (I think) even without labels/tags support. I'm going to try hacking around a bit and see if I can get something to work.
