### ISSUE TITLE
Suggestion: use .conf instead of .toml as extension for configuration

### ISSUE THREAD

**Issue by pkieltyka** [EmileVauge/traefik#19]
TOML is great. I use it too, but I find the .conf extension is nicer and I've seen others do this as well.

**Comment by vdemeester** [comment]
@pkieltyka thanks for the issue. I think this is not really a problem as you can specify a configuration file with any extension, so : `traefik my.conf` will work as long as it's a valid `toml` file and traefik configuration file.

From my point of view it's just a matter of *samples* but that's all.

/cc @EmileVauge

**Comment by pkieltyka** [comment]
sure, but usually people adopt conventions you lay out in your README. it was just a suggestion, I'm just an observer.

**Comment by vdemeester** [comment]
@pkieltyka yeah that's what I though :wink:. I'm fine to add a little thingy in the README to say `.conf` or `.toml` or … is ok, but I'll let @EmileVauge give his opinion :stuck_out_tongue_closed_eyes:.

**Comment by EmileVauge** [comment]
Hi,
As seen in issue https://github.com/EmileVauge/traefik/issues/7#issuecomment-142380194, I would like to integrate viper to manage configuration files. It will then be possible to provide an YAML, TOML or json configuration file to suit your needs. It appears that it will be difficult to change the extension :)

**Comment by pkieltyka** [comment]
yuck
