### ISSUE TITLE
Web based dashboard gives me "404 page not found"

### ISSUE THREAD

**Issue by akunaatrium** [emilevauge/traefik#190]
I don't know if they are connected or not but logs include this line:

time="2016-02-10T14:20:20Z" level=error msg="Failed to register for subscriptions, http event callback system is not running on this Marathon instance. Please re-start this instance with \"--event_subscriber http_callback\"."

If Marathon needs to have this event_subscriber option defined for Traefik dashboard, it should be documented accordingly.

**Comment by emilevauge** [comment]
Hi @akunaatrium, which version of traefik are you using?
- 404 error: no sure that it is linked to Marathon issue. First, do you mean the [Web UI](https://github.com/EmileVauge/traefik#web-ui)? Could you give use your traefik.toml?
- Marathon Issue: indeed, you have to launch marathon with this option (we should update the doc...), like [here](https://github.com/emilevauge/traefik/blob/master/tests/compose-marathon.yml).

**Comment by akunaatrium** [comment]
Yes, I meant the Web UI. I started Traefik with this command so I guess it's the latest version:

`docker run --rm -p 7878:80 -v `pwd`/traefik/traefik.toml:/traefik.toml -v `pwd`/traefik/logs:/logs emilevauge/traefik`

The traefik.toml file looks like this:

```
traefikLogsFile = "/logs/traefik.log"
accessLogsFile = "/logs/access.log"
logLevel = "DEBUG"

[web]
address = ":7878"

[marathon]

endpoint = "http://10.0.0.5:8080"
networkInterface = "eth0"
watch = true
domain = "marathon.localhost"
```

**Comment by emilevauge** [comment]
if you use that in your TOML file:
```
[web]
address = ":7878"
```
You have to launch your container using:

```
docker run --rm -p 7878:7878 -vpwd/traefik/traefik.toml:/traefik.toml -vpwd/traefik/logs:/logs emilevauge/traefik
```

You will be able to access web UI on port `7878` ;)

**Comment by akunaatrium** [comment]
Oh, nice, indeed. I got the impression from somewhere that the web server listens on port 80 in the container and I need to map some host port to the container port. But looks like I was wrong :) Thanks!
