### ISSUE TITLE
docker path

### ISSUE THREAD

**Issue by navinSing** [emilevauge/traefik#202]
ideally it should be a directory like /config .. rather than /
Or docker "command" must allow to take config in other dir  
this will allow to pass multiple files
and recommended

**Comment by vdemeester** [comment]
@navinSing I'm not sure to understand the issue. Do you talk about the `endpoint` option of the docker backend, or something else ?

**Comment by navinSing** [comment]
yes endpoint .. 
with the current endpoint you can't specify the the toml file at otherr locations 

like /config/traefik.toml

**Comment by vdemeester** [comment]
@navinSing It's still not pretty clear to me.

- If it's about the docker endpoint, it support any docker engine syntax, like `tcp://…` or `unix://…` URI. And it does not make sense to point to multiple one.
- If it's about specifying the `traefik` configuration file, it depends the version you are running. On the current version (based on `master`), you can use `traefik --configFile=fixtures/file/simple.toml` to point to a specified configuration. *On previous version, it used to be `traefik fixtures/file/simple.toml` but it has change*. Not that I don't think it supports multiple file (yet?).

/cc @emilevauge

**Comment by navinSing** [comment]
nah .. actually i am using a separate rules.toml
just for simplicity i wanted all the toml files in one dir .. since i do have logs etc.. 
what will be docker command with --configFile

**Comment by emilevauge** [comment]
@navinSing, what backend do you use? Docker? File?
Using file backend with one global config file and one for rules:
`traefik --configFile=/whatyouwant/traefik.toml --file --file.filename=/whatyouwant/rules.toml --file.watch`
Using Docker backend:
`traefik --configFile=/whatyouwant/traefik.toml --docker --docker.endpoint=unix:///var/run/docker.sock --docker.watch --docker.domain=docker.local`
