### ISSUE TITLE
No CA certificates in official docker image

### ISSUE THREAD

**Issue by vandot** [EmileVauge/traefik#21]
Trying to proxy to https backend generates an error:
level=error msg="Error forwarding to https://, err: x509: failed to load system roots and no roots provided"

**Comment by EmileVauge** [comment]
Hi, thank you for reporting.
I will fill the image with CA certs.

**Comment by vdemeester** [comment]
@vandot as soon as the image is published on the hub, it should be ok. Let us know that works for you and we'll close this one :wink:

**Comment by vandot** [comment]
@vdemeester It works, thanks :)
