### ISSUE TITLE
Traefik Crashes -- various

### ISSUE THREAD

**Issue by Ozzadar** [EmileVauge/traefik#44]
Was doing some stress testing with some app deployment/teardown and found a few cases where Traefik is dying on us =(

I quickly deployed 100 ghost blogs and Traefik crashed.

After tearing down those containers and relaunching Traefik, I managed to relaunch 100 ghost blogs successfully but Traefik crashed when I tore them down.

Don't know what would be causing this but it would be awesome if there was a fix :)

I'll do some more stress tests and try and capture some logs to attach to this in the next day or two.

- Ozzadar

**Comment by EmileVauge** [comment]
Hey! This one may be linked to https://github.com/EmileVauge/traefik/issues/37, correction is coming is the day.
Let me know when you have logs :)

**Comment by EmileVauge** [comment]
Any news @Ozzadar ?

**Comment by Ozzadar** [comment]
Hey, been super busy. 

So I'm running a bunch of customized front end back end and front end stress tests this week on our site and will make sure traefik is logging it's side of things so I can attach the results. And the specifics of everything being done to it. 

It hasn't crashed through hundreds of deployments over the last few days, though Ive been trying to send it no more than 1request/ sec though. This week will hurt poor traefik I think has

I'll keep you posted

**Comment by EmileVauge** [comment]
Closing this one. @Ozzadar, please create another issue if you get trashes again :)
