### ISSUE TITLE
systemd unit file

### ISSUE THREAD

**Issue by faddat** [emilevauge/traefik#58]
We're working on a unit file for traefik.  

@EmileVauge -- 1000x, thank you!  Your project has made our project possible.  
@ozzadar -- can you toss your proto-unit-file in here?

**Comment by EmileVauge** [comment]
@faddat Thanks ! Great to hear that :)

**Comment by keis** [comment]
Hi @faddat any update on this?

**Comment by emilevauge** [comment]
Fixed by #172
