### ISSUE TITLE
Memory & CPU usage rise over time

### ISSUE THREAD

**Issue by faddat** [emilevauge/traefik#59]
@EmileVauge 

Traefik's latency seemed pretty high-- I didn't know if it is our setup, the nature of traefik's dynamic configuration, or nothing at all to be concerned with.  Here's what our CPU graph on google looks like:

![image](https://cloud.githubusercontent.com/assets/7142025/10419104/ec07519a-7096-11e5-8ac9-2090e6104c8b.png)

You can see where I reset traefik-- it dropped off nicely then.  Also, average latency went from ~3.5s to 75ms.  How do you test something like traefik?  I am about to:
```bash
         #!/bin/bash 
         COUNTER=0
         while [  $COUNTER -lt 1000000 ]; do
             echo The counter is $COUNTER
			 curl http://faddat-p4nbgmug-gogs.klouds.org/explore
             let COUNTER=COUNTER+1 
         done
```
Effective?  Insane?  Pointless?  

Thank you :)

**Comment by faddat** [comment]
![image](https://cloud.githubusercontent.com/assets/7142025/10419145/27496116-7098-11e5-8edd-979ae0e4ea5a.png)


Suppose that means trae passed this test!  How else can we mess with it?

**Comment by faddat** [comment]
I tweaked the script a little bit to make it enrage trae more.  I was not successful:

![image](https://cloud.githubusercontent.com/assets/7142025/10419174/2419f9aa-7099-11e5-9110-fdde8ab25529.png)

#toss in a URL or two, see how it goes....
#!/bin/bash 
COUNTER=0
while [  $COUNTER -lt 1000000 ]; do
echo The counter is $COUNTER
#to make your systems extra crazy, you could put multiple URLs here
curl http://ozzadar-4psaxe23-ghost.klouds.org/welcome-to-ghost/
curl http://ozzadar-conn96gn-ghost.klouds.org/welcome-to-ghost/
curl http://ozzadar-yiitrnhq-etherpad.klouds.org/p/chickenfart
let COUNTER=COUNTER+1 
done

**Comment by faddat** [comment]
![image](https://cloud.githubusercontent.com/assets/7142025/10419221/ef10340c-709a-11e5-9808-bb3816339c99.png)

**Comment by faddat** [comment]
![image](https://cloud.githubusercontent.com/assets/7142025/10419215/d745e7c2-709a-11e5-9b57-00652f24ebc2.png)

**Comment by faddat** [comment]
![image](https://cloud.githubusercontent.com/assets/7142025/10419635/7f8bb69e-70a7-11e5-9d83-b86c5a618547.png)

**Comment by EmileVauge** [comment]
Hi @faddat , Thank you for reporting :)
Could you give a bit more information on you configuration? Your traefik.toml file for exemple.
What are you calling "reseting" Traefik?
About benchmarks, you can get more here https://github.com/EmileVauge/traefik/blob/master/docs/index.md#benchmarks. I would advise to use `ab` to make concurrent requests on Traefik.

**Comment by emilevauge** [comment]
@faddat, any news on this ?

**Comment by faddat** [comment]
@emilevauge -- I can't, it's not in our stack at the moment-- should I close the issue for now or...?

**Comment by emilevauge** [comment]
Ok, closing this one for now :) thanks!
