### ISSUE TITLE
Path based routing for API gateways

### ISSUE THREAD

**Issue by solher** [emilevauge/traefik#73]
I may have missed something but currently, Traefik seems to only allow domain based routing.
For example with Docker microservices:
userService.docker.com -> user service container
resourceService.docker.com -> resource service container

To allow an API gateway usage, shouldn't path based routing be possible too ?
Like:
app.docker.com/userService -> user service container
app.docker.com/resourceService -> resource service container

**Comment by emilevauge** [comment]
@solher Hi, you are right, this is not possible today, using the Docker backend. Maybe we should refactor the labels.
Today, you can use the label `traefik.host=bar`.
We could introduce two labels instead:
- `traefik.frontend.rule=Host`
- `traefik.frontend.value=test.localhost`

This way, we could also use:

- `traefik.frontend.rule=Path`
- `traefik.frontend.value=/test`

This should be implemented with Marathon backend.

@vdemeester , @solher sounds OK?

**Comment by solher** [comment]
Sounds simple and efficient to me. Thanks a lot !

**Comment by thorhs** [comment]
I implemented something similar for the Marathon plugin, I don't remember
the method I used.  I think I added a new attribute.

It might be good to refactor this out of the config plugins somehow, to
have a consistent way of configuring.

Thor

**Comment by vdemeester** [comment]
I like the idea of `traefik.frontend.rule` but I would definitely think that we should have a default one (Host for example), so if not specified, it uses this one (just to make it simple :stuck_out_tongue: ).

**Comment by emilevauge** [comment]
@thorhs you're right, we could refactor a bit what you've done in your PR for Marathon :)
@vdemeester this is already the case, when you start a container without label, you ends up with a routing `{containerName}.{domain}` ;)

**Comment by emilevauge** [comment]
One more thing: for now, there is no URL rewriting mechanism in traefik, just to be clear ;)

**Comment by bbinet** [comment]
Is it possible to combine both Path-based and Host-based rules to route traffic to the backends? I'd like to route the requests based on more complex rules that would be built by combining simple Host/Path-based rules using logical operators such as "and", "or", "not"...

Sorry if I missed to relevant documentation, but I couldn't find anything on the https://docs.traefik.io website.

**Comment by bbinet** [comment]
Thanks @emilevauge

**Comment by allamand** [comment]
@emilevauge 

> One more thing: for now, there is no URL rewriting mechanism in traefik, just to be clear ;)
>Your call to app.docker.com/userService will ends up at {container-ip}/userService.

Is there a plan to add some rewriting mechanisms ?

thanks

**Comment by sagikazarmark** [comment]
Without the rewritting mechanism this kind of routing doesn't really help in acting as an API gateway.
