### ISSUE TITLE
Support for WebSockets

### ISSUE THREAD

**Issue by andyshinn** [EmileVauge/traefik#8]
One major reason why I haven't been able to play with something like vulcand is the lack of WebSocket support. This may not be high on the priority list. But support for WebSockets would make this much more viable to me as a replacement for my more kudgly HAProxy and nginx reverse proxy setups in Docker.

**Comment by EmileVauge** [comment]
Hi!
I will try in the next days to do this in a middeware using https://gist.github.com/sheenobu/5aad1b1c07e9ff52eefe :)

**Comment by andyshinn** [comment]
Cool, yea a middleware seems like the best place to do it. I saw that patch as well. And I'm sure you are also aware of https://github.com/gorilla/websocket. Not sure which might be easier to implement.

**Comment by sheenobu** [comment]
@EmileVauge Let me know how it goes. I saw that this was mailgun/oxy based and wondered if it reacted to websockets in the same way.

**Comment by gngeorgiev** [comment]
Websocket support is what will would make me try this in favor of HAProxy, as a matter of fact this is why I did not try out vulcand.

**Comment by EmileVauge** [comment]
If interested, I created a branch with websocket alpha support taken from https://gist.github.com/sheenobu/5aad1b1c07e9ff52eefe:
https://github.com/EmileVauge/traefik/tree/websockets-support

**Comment by jpillora** [comment]
+1

**Comment by dekobon** [comment]
+1

**Comment by JonnyBGod** [comment]
+1

Would like to propose also support for http/2 and server sent events.

**Comment by tboerger** [comment]
If the websocket support gets integrated I really have to switch to traefik from vulcand :)

**Comment by jpillora** [comment]
Nice work @EmileVauge, I'll try swapping vulcan out for traefik tonight :)
