### ISSUE TITLE
Filter Marathon events that fail health checks or are not running

### ISSUE THREAD

**Issue by stevendborrelli** [emilevauge/traefik#81]
We've seen some 503 issues in our deployment and think it is related to the way marathon describes tasks. 

For example, in https://mesosphere.github.io/marathon/docs/rest-api.html#get-v2-tasks, we can filter tasks that are staged but not running

We should also have the ability to filter tasks that fail a health check.

**Comment by emilevauge** [comment]
Hi @stevendborrelli, thanks for reporting :)
You are absolutely right, we need to filter staging tasks from being routed.
I think that if a task is in `running` status, that means that its health check is ok.
Therefore, it should be OK to only filter on status.
OK for you?

**Comment by stevendborrelli** [comment]
Sounds good! We have a cluster here we can test on.

**Comment by emilevauge** [comment]
Well, the go API doesn't allow to filter tasks by status, I will use healthcheck result instead...
https://github.com/gambol99/go-marathon/blob/master/task.go

**Comment by emilevauge** [comment]
Created an issue https://github.com/gambol99/go-marathon/issues/81 on that point ;)

**Comment by emilevauge** [comment]
A PR has been made on go-marathon: https://github.com/gambol99/go-marathon/pull/82. I will use this feature in traefik to get only running tasks.
