### ISSUE TITLE
URL Variables as Docker Labels?

### ISSUE THREAD

**Issue by polds** [emilevauge/traefik#98]
Wondering if it's possible to do URL Variables as part of a Docker label like so:

```
docker run ... \
  --label traefik.frontend.rule=Host \
  --label traefik.frontend.value={subdomain:[a-z]+}.example.com \
  ...
```

**Comment by polds** [comment]
Looked into it a little more when trying to pass that as a Docker label the toml package throws the following error:

`Error creating docker configuration Near line 8, key 'frontends': Near line 8: Table names cannot contain '[' or ']'.`

Looks like because the entire frontend name is being used as per [docker.tmpl](https://github.com/emilevauge/traefik/blob/master/templates%2Fdocker.tmpl#L8) it's attempting also inject the regex into the table name.

Please see the referenced commit for my fixes. If you think these are inline I can make a PR. I'm not exactly sure what to return with if the parsing failed. Right now it returns the original string (Don't like this)

**Comment by emilevauge** [comment]
Hi @polds, thank you for reporting. This is an issue. We have to find a smart way to do that. I'm not sure to understand what does:
```go
"makeParsedUrl": func(s1 string) string {
			if u, err := url.Parse(s1); err == nil {
				return u.String()
			}
			return s1
		},
```
Could you explain a little bit ?

**Comment by polds** [comment]
@emilevauge it converts the string to their html entities counterparts. Going in the string is `{subdomain: [a-z]+}.example.com` and coming back it is converted to an ugly but safe: `%7Bsubdomain:%20%5Ba-z%5D+%7D.example.com` but still parsed correctly by Traefik.

My biggest concern is if the `url.Parse()` fails I have it returning the same string which would inevitably cause issues if `url.Parse()` can't handle it. I'm wondering if just returning the string "error" would be better.

**Comment by emilevauge** [comment]
@polds, OK I get it. I definitely prefer the second solution to reuse the `replace` template function. Would you make a PR on that point?

**Comment by emilevauge** [comment]
Or even better, should be added directly here: https://github.com/emilevauge/traefik/blob/master/provider/docker.go#L209
